name: Extract and Store M3U Groups

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  extract-m3u-groups:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run M3U extraction script
      env:
        M3U_URL: "https://fy.188766.xyz/?url=https://live.188766.xyz&mishitong=true&mima=bingchawusifengxian&huikan=1"
      run: |
        python .github/scripts/extract_m3u.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add live*.m3u
        git diff --staged --quiet || git commit -m "Update M3U group files - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
